### PR TITLE
Fix portrait mode dimensions

### PR DESCRIPTION
**Pull request by rojer**

### CODE REVIEW

**Comment by pimvanpelt** [comment]
Understood on the fix you're proposing but why use the defines? There are ILI9341 screens with different dimensions (like the 3.5" Adafruit unit at 480x320):
https://learn.adafruit.com/adafruit-3-5-tft-featherwing/overview

The intention was to set the dimensions in the application like so:
```
mgos_ili9341_set_dimensions(mgos_sys_config_get_tft_width(), mgos_sys_config_get_tft_height());
```
and tft.width / tft.height in `mos.yml`. Would it be enough to simply swap width/height in line 268?

**Comment by rojer** [comment]
hm, ok. i didn't realize they came in a variety of resolutions.
shall we add these two as config settings then?

**Comment by rojer** [comment]
ok, swapping width and height fixes the issue at hand, so let's just do that for now.
PTAL.

**Comment by pimvanpelt** [comment]
Looks fine (and fixes an obvious bug on portrait screen dimensions). I will add ili9341.width/height now.

**Comment by pimvanpelt** [comment]
Added ili9341.width and ili9341.height flags to `mos.yml` in https://github.com/mongoose-os-libs/ili9341-spi/commit/16a0a393fe6a8517cd126d05a10f210b234fc31e

**Pull request merged**
